config/routes.rb
Rails.application.routes.draw do
  root to:"restaurants#index"
  resources :restaurants
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  scope :by_new, ->{ order(updated_at: :desc) }
  validates :title, presence: true
  validates :body, presence: true
  validates :title, uniqueness: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :telephone, presence: true
  validates :name, uniqueness: true
  scope :by_id, ->{ order(id: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:edit, :show, :update, :destroy]
  def show
  end  

  def index
    @articles = Article.all.by_new
  end

  def new
    @article = Article.new 
  end  

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else 
      render 'new'
    end    
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render 'edit'
    end  
  end  

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params[:article].permit(:title, :body,)
  end

  def set_article
    @article = Article.find(params[:id])
  end  
end  

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only:[:edit, :show, :update, :destroy]
  def show
  end
  
  def index
    @restaurants = Restaurant.all.by_id
  end
  
  def new
    @restaurant = Restaurant.new  
  end 
  
  def create
    @restaurant = Restaurant.new(restaurant_params)  
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new' 
    end
  end   

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurants_path(@restaurant)
    else
      render 'edit'  
    end
  end
  
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end  

  private

  def restaurant_params
    params[:restaurant].permit(:name, :address, :telephone)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end  
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
=bootstrap_form_with model: @article, local: true do |f|
  =f.text_field :title
  =f.text_field :body
  =f.submit
=link_to'トップに戻る', articles_path

app/views/articles/edit.html.haml
=render 'form'

app/views/articles/index.html.haml
-@articles.each do |article|
  タイトル:
  =link_to article.title, article_path(article.id)
  %br  
  本文:
  =article.body
  %hr
=link_to '新規登録', new_article_path

app/views/articles/new.html.haml
%h2 新規登録 
=render 'form'

app/views/articles/show.html.haml
=@article.title
=@article.body
=link_to 'トップに戻る', articles_path
=link_to '編集', edit_article_path(@article)
=link_to '削除', article_path(@article), method: :delete, data: {confirm: "削除しますか？"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Restaurant
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield
    = javascript_include_tag "application"

app/views/restaurants/_form.html.haml
=bootstrap_form_with model: @restaurant, local: true do |f|
  =f.text_field :name
  =f.text_field :address
  =f.text_field :telephone
  =f.submit
=link_to'トップに戻る', restaurants_path

app/views/restaurants/edit.html.haml
%h2 編集
=render 'form'

app/views/restaurants/index.html.haml
-@restaurants.each do |restaurant|
  名前:
  =link_to restaurant.name, restaurant_path(restaurant.id)
  %br  
  住所:
  =restaurant.address
  %br
  電話番号:
  =restaurant.telephone
  %hr
=link_to '新規登録', new_restaurant_path

app/views/restaurants/new.html.haml
%h2 新規登録 
=render 'form'

app/views/restaurants/show.html.haml
=@restaurant.name 
=@restaurant.address
=@restaurant.telephone
=link_to 'トップに戻る', restaurants_path
=link_to '編集', edit_restaurant_path(@restaurant)
=link_to '削除', restaurant_path(@restaurant), method: :delete, data: {confirm: "削除しますか？"}